"""Add thumbnail_url

Revision ID: 3aaaefd81b0a
Revises: 06be06b593b4
Create Date: 2026-08-09 12:55:43.972908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaaefd81b0a'
down_revision: Union[str, None] = '06be06b593b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('event_participations', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('internships', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('patents', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('research_publications', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_publications', 'thumbnail_url')
    op.drop_column('patents', 'thumbnail_url')
    op.drop_column('internships', 'thumbnail_url')
    op.drop_column('event_participations', 'thumbnail_url')
    op.drop_column('certificates', 'thumbnail_url')
    # ### end Alembic commands ###
