"""drop certificates table

Revision ID: 6a30aab657aa
Revises: ffc0eafda47c
Create Date: 2026-08-09 14:51:05.141536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a30aab657aa'
down_revision: Union[str, None] = 'ffc0eafda47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS certificates CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('cert_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('issuer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('fdp', 'external', 'nptel', 'ieee', name='certificatecategory'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='certificates_student_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], name='certificates_verified_by_fkey'),
    sa.PrimaryKeyConstraint('cert_id', name='certificates_pkey')
    )
    # ### end Alembic commands ###
