"""add publications, patents, internships, event participations

Revision ID: 7826a8516734
Revises: 7a6c82869f97
Create Date: 2026-07-31 00:03:16.901709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7826a8516734'
down_revision: Union[str, None] = '7a6c82869f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# certificatestatus already exists (created by the certificates table in
# the previous migration) and ownertype/participationrole are each used by
# more than one table in this migration -- CREATE TYPE must run exactly
# once per type, not once per column, so these are created explicitly and
# every column below references them with create_type=False.
certificate_status = postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus', create_type=False)
owner_type = postgresql.ENUM('student', 'employee', name='ownertype')
participation_role = postgresql.ENUM('participant', 'organizer', name='participationrole')


def upgrade() -> None:
    bind = op.get_bind()
    owner_type.create(bind, checkfirst=True)
    participation_role.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participations',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=300), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participation_role', postgresql.ENUM('participant', 'organizer', name='participationrole', create_type=False), nullable=False),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype', create_type=False), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', certificate_status, nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('internships',
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype', create_type=False), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', certificate_status, nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('internship_id')
    )
    op.create_table('patents',
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('patent_number', sa.String(length=120), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype', create_type=False), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', certificate_status, nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('patent_id')
    )
    op.create_table('research_publications',
    sa.Column('pub_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype', create_type=False), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', certificate_status, nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('pub_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_publications')
    op.drop_table('patents')
    op.drop_table('internships')
    op.drop_table('event_participations')
    # ### end Alembic commands ###

    bind = op.get_bind()
    participation_role.drop(bind, checkfirst=True)
    owner_type.drop(bind, checkfirst=True)
