"""initial schema

Revision ID: 7a6c82869f97
Revises: 
Create Date: 2026-07-30 23:11:18.064094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6c82869f97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('projects',
    sa.Column('proj_id', sa.Integer(), nullable=False),
    sa.Column('proj_name', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('proj_id')
    )
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('principal', 'admin_hod', 'admin_clerk', 'faculty_coordinator', name='employeerole'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.dept_id'], ),
    sa.PrimaryKeyConstraint('emp_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dependents',
    sa.Column('dep_name', sa.String(length=120), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('dep_name', 'employee_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('student_type', sa.Enum('inhouse', 'outhouse', name='studenttype'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.dept_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('certificates',
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('fdp', 'external', 'nptel', 'ieee', name='certificatecategory'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='certificatestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('cert_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    op.drop_table('students')
    op.drop_table('dependents')
    op.drop_table('employees')
    op.drop_table('projects')
    op.drop_table('departments')
    # ### end Alembic commands ###
