"""Add unified Achievement table

Revision ID: ffc0eafda47c
Revises: 3aaaefd81b0a
Create Date: 2026-08-09 13:43:50.156494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc0eafda47c'
down_revision: Union[str, None] = '3aaaefd81b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('metadata_fields', sa.JSON(), nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype', create_type=False), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus', create_type=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_participations')
    op.drop_table('patents')
    op.drop_table('research_publications')
    op.drop_table('internships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('internship_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], name='internships_employee_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='internships_student_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], name='internships_verified_by_fkey'),
    sa.PrimaryKeyConstraint('internship_id', name='internships_pkey')
    )
    op.create_table('research_publications',
    sa.Column('pub_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('venue', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('publication_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], name='research_publications_employee_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='research_publications_student_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], name='research_publications_verified_by_fkey'),
    sa.PrimaryKeyConstraint('pub_id', name='research_publications_pkey')
    )
    op.create_table('patents',
    sa.Column('patent_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('patent_number', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('filing_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], name='patents_employee_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='patents_student_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], name='patents_verified_by_fkey'),
    sa.PrimaryKeyConstraint('patent_id', name='patents_pkey')
    )
    op.create_table('event_participations',
    sa.Column('event_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('participation_role', postgresql.ENUM('participant', 'organizer', name='participationrole'), autoincrement=False, nullable=False),
    sa.Column('owner_type', postgresql.ENUM('student', 'employee', name='ownertype'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='certificatestatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.emp_id'], name='event_participations_employee_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='event_participations_student_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.emp_id'], name='event_participations_verified_by_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='event_participations_pkey')
    )
    op.drop_table('achievements')
    # ### end Alembic commands ###
